import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes `com.ilyne.helloszigetkmp.core.config.SzigetBuildConfig` — the generated Kotlin object
 * that carries build-time-overridable app config (local backend URL, dev bearer token, skip
 * Google Sign-In) into `:shared`'s commonMain. See :shared's build.gradle.kts for how the field
 * values are resolved (project property, else local.properties) and how this task's output is
 * wired into the commonMain source set.
 *
 * A dedicated task type (rather than an ad-hoc `tasks.registering { doLast { ... } }`) so this
 * only touches Gradle-managed Property/DirectoryProperty inputs. Those are config-cache-
 * serializable; closures capturing a build script's top-level `val`s at execution time are not
 * (the script instance they're members of isn't serializable).
 */
abstract class GenerateSzigetBuildConfigTask : DefaultTask() {
    @get:Input
    abstract val localBackendUrl: Property<String>

    @get:Input
    abstract val localBearerToken: Property<String>

    @get:Input
    abstract val skipGoogleSignIn: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        // Escaped since these values are spliced directly into a Kotlin string literal below.
        fun String.toKotlinStringLiteral() = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")

        val packageDir = outputDir.get().dir("com/ilyne/helloszigetkmp/core/config").asFile
        packageDir.mkdirs()
        File(packageDir, "SzigetBuildConfig.kt").writeText(
            """
            |package com.ilyne.helloszigetkmp.core.config
            |
            |// Generated by :shared's generateSzigetBuildConfig Gradle task from the
            |// sziget.localBackendUrl / sziget.localBearerToken / sziget.skipGoogleSignIn
            |// properties (project property, else local.properties). Do not edit by hand.
            |internal object SzigetBuildConfig {
            |    const val LOCAL_BACKEND_URL: String = "${localBackendUrl.get().toKotlinStringLiteral()}"
            |    const val LOCAL_BEARER_TOKEN: String = "${localBearerToken.get().toKotlinStringLiteral()}"
            |    const val SKIP_GOOGLE_SIGN_IN: Boolean = ${skipGoogleSignIn.get()}
            |}
            |
            """.trimMargin(),
        )
    }
}
